[build]
  command = "npm run build && npm run export"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.19.0"
  NEXT_PRIVATE_SKIP_CACHE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200