import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "@/contexts/AuthContext";
import ConditionalFooter from "@/components/ConditionalFooter";
import { GlobalDataProvider } from "@/contexts/GlobalDataContext";
import { ImageLoadingProvider } from "@/lib/services/imageLoaderService";

export const metadata = {
  title: "GDC Properties",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <GlobalDataProvider>
            <ImageLoadingProvider>
              <Header />
              {children}
              <ConditionalFooter />
            </ImageLoadingProvider>
          </GlobalDataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}