// app/layout.js (keep as server component)
import "./globals.css";
import ClientProviders from "./ClientProviders";

export const metadata = {
  title: "GDC Properties",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}