"use client";

import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/contexts/AuthContext";
import { ImageLoadingProvider } from "@/lib/services/imageLoaderService";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Client component to conditionally render footer
function ConditionalFooter() {
  const pathname = usePathname();
  
  // Skip rendering footer on dashboard page
  if (pathname?.startsWith('/dashboard')) {
    return null;
  }
  
  return <Footer />;
}

export default function RootLayout({ children }) {
  const pathname = usePathname();
  
  // Create metadata (since this is now a client component, we can't export const metadata)
  const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Header />
          <ImageLoadingProvider>{children}</ImageLoadingProvider>
          <ConditionalFooter />
        </AuthProvider>
      </body>
    </html>
  );
}